---

- name: Disable SELinux
  selinux:
    state: disabled

- name: install barman 
  yum:
    name: barman
    state: present

- name: create barman user
  become_user: postgres
  shell: psql -U postgres -c "CREATE USER barman WITH SUPERUSER"

- name: copy barman configuration
  copy:
    src: barman.conf
    dest: /etc/barman.conf
    mode: 0644

- name: create ssh dir for barman
  file:
    path: "/var/lib/barman/.ssh"
    state: directory
    owner: barman
    group: barman
    mode: 0700

- name: copy ssh keys
  copy: src=files/.ssh/{{ item }} dest=/var/lib/barman/.ssh/ mode=0600 owner=barman group=barman
  with_items:
    - authorized_keys

- name: create replication slot
  shell: barman receive-wal --create-slot master

- name: switch-xlog
  shell: barman switch-xlog --force --archive master